version: "3.8"
services:
  db:
    image: postgres:15
    container_name: fastapi_project_db
    command: ['-p 5430']
    expose:
      - 5430
    env_file:
      - .env-non-dev
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_project_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8888:8000
    depends_on:
      - db